### PR TITLE
windows bugfix

### PR DESCRIPTION
**Pull request by kiwi0fruit**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
@conda-forge-admin, please rerender

**Comment by kiwi0fruit** [comment]
@ocefpaf please merge PR

**Comment by kiwi0fruit** [comment]
@ocefpaf please merge the PR

**Comment by ocefpaf** [comment]
> @ocefpaf please merge the PR

@kiwi0fruit no need to ping me repeatedly like that. Sometimes we do take breaks ;-p

**Pull request merged**
