### PR TITLE
Fix License identifier

### PR DESCRIPTION
**Pull request by pavelzw**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

The license is actually Apache-2.0: https://github.com/c-w/ghp-import/blob/master/LICENSE

I also verified that the sdist ships the same Apache-2.0 license file

### CODE REVIEW

**Comment by pavelzw** [comment]
ci doesn't start because of https://github.com/conda-forge/status/issues/188

**Comment by ocefpaf** [comment]
@conda-forge-admin, please restart ci

**Comment by ocefpaf** [comment]
@pavelzw can you try to send an empty commit here to see if that kicks the CIs into motion?

**Comment by pavelzw** [comment]
```
The following packages are incompatible
└─ conda-forge-ci-setup 3**  is installable with the potential options
   ├─ conda-forge-ci-setup [3.0.10|3.0.11|...|3.9.6] would require
   │  └─ python >=3.6,<3.7.0a0 , which can be installed;
   ├─ conda-forge-ci-setup [3.0.10|3.0.11|...|3.9.6] would require
   │  └─ python >=3.7,<3.8.0a0 , which can be installed;
   ├─ conda-forge-ci-setup [3.0.14|3.1.0|...|3.9.6] would require
   │  └─ python >=3.8,<3.9.0a0 , which can be installed;
   ├─ conda-forge-ci-setup [3.10.0|3.10.1|...|3.9.6] would require
   │  └─ python >=3.9,<3.10.0a0 , which can be installed;
   ├─ conda-forge-ci-setup [3.17.1|3.18.0|...|3.34.1] would require
   │  └─ python >=3.10,<3.11.0a0 , which can be installed;
   └─ conda-forge-ci-setup [3.21.0|3.22.0|...|3.34.1] would require
      └─ python >=3.11,<3.12.0a0 , which can be installed.
```

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
